- name: Install and configure Nginx with 2 virtual hosts on Ubuntu
  hosts: db                         
  become: yes
  tasks:
    # 1. Nginx 설치
    - name: Install Nginx
      apt:
        name: nginx
        state: present                     
        update_cache: yes                   

    # 2. 두 개의 가상 서버 설정 파일을 생성
    - name: Create the configuration for x.com
      copy:
        dest: /etc/nginx/sites-available/x.com     
        content: |
          server {
              listen 80;
              server_name www.x.com;

              root /var/www/x;                     
              index index.html;

              location / {
                  try_files $uri $uri/ =404;
              }
          }

    # 3. 가상 서버를 sites-enabled에 심볼릭 링크 생성
    - name: Enable x.com site
      file:
        src: /etc/nginx/sites-available/x.com  
        dest: /etc/nginx/sites-enabled/x.com    
        state: link                             

    # 4. 웹 콘텐츠 디렉토리 생성
    - name: Create directory for x.com         
      file:
        path: /var/www/x                      
        state: directory                         

    # 5. 각 도메인에 대한 기본 index.html 파일 생성
    - name: Create index.html for x.com
      copy:
        dest: /var/www/x/index.html
        content: "Welcome to x.com"

    # 6. Nginx 구문 테스트
    - name: Test nginx configuration
      command: nginx -t

    # 7. Nginx 재시작
    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
